import React, { useState, useEffect } from 'react';
import { Download, FileText, CheckCircle, Share2, Printer, Loader2, RefreshCw } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { useAuth } from '@clerk/nextjs';
import { getAuditLogs, AuditRecord } from '@/services/api';

export default function BenefitReceiptViewer() {
  const { getToken } = useAuth();
  const [receiptLog, setReceiptLog] = useState<AuditRecord | null>(null);
  const [isPolling, setIsPolling] = useState(true);

  // State variables for SMS mock panel, initialized once lazy to avoid impure render lints
  const [txHash] = useState(() => `0x${Math.random().toString(16).slice(2, 10)}...${Math.random().toString(16).slice(2, 6)}`);
  const [txTimestamp] = useState(() => new Date().toISOString());

  useEffect(() => {
    let interval: NodeJS.Timeout;
    const fetchLatestReceipt = async () => {
      try {
        const token = await getToken();
        const logs = await getAuditLogs(token);
        // Find the most recent successful eligibility check
        const latestEligible = logs.reverse().find(
          (log) => log.record_type === 'eligibility' && log.payload?.eligible === true
        );
        if (latestEligible) {
          setReceiptLog(latestEligible);
        }
      } catch (err) {
        console.error("Failed to fetch receipt data", err);
      }
    };

    if (isPolling) {
      fetchLatestReceipt();
      interval = setInterval(fetchLatestReceipt, 3000);
    }
    return () => clearInterval(interval);
  }, [isPolling, getToken]);

  const receiptId = String(receiptLog?.payload?.case_id || receiptLog?.record_id?.substring(0, 12) || 'JSN-WAITING...');
  const schemeName = String(receiptLog?.payload?.scheme || 'Scanning...');
  const rulesTrace = (receiptLog?.payload?.rules_trace as string[]) || [];

  return (
    <div className="flex flex-col h-full space-y-6 max-w-6xl mx-auto w-full">
      <div className="flex justify-between items-end">
        <div>
          <h2 className="text-2xl font-bold tracking-tight flex items-center gap-3">
            <FileText className="w-6 h-6 text-blue-500" />
            Citizen Benefit Receipts
          </h2>
          <p className="text-secondary-foreground text-sm mt-1">Generated by L6 Action Layer. Cryptographically hashed and ready for offline use.</p>
        </div>
        <div className="flex items-center gap-3">
          <button onClick={() => setIsPolling(!isPolling)} className={`p-2 rounded-xl transition-colors ${isPolling ? 'text-emerald-500 bg-emerald-500/10' : 'text-secondary-foreground bg-secondary'}`}>
            <RefreshCw className={`w-4 h-4 ${isPolling ? 'animate-spin-slow' : ''}`} />
          </button>
          <button className="px-4 py-2 bg-blue-500 hover:bg-blue-600 text-white font-bold rounded-lg text-sm flex items-center gap-2 transition-colors">
            <Download className="w-4 h-4" /> Export All (PDF)
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* Receipt Document Preview */}
        <div className="col-span-1 lg:col-span-2 bg-white text-black p-8 sm:p-12 rounded-xl shadow-2xl relative overflow-hidden min-h-[600px] border border-border">
          {/* Watermark */}
          <div className="absolute inset-0 flex items-center justify-center opacity-[0.03] pointer-events-none">
            <div className="text-[150px] font-bold transform -rotate-45">JANSATHI</div>
          </div>

          <div className="relative z-10 h-full flex flex-col">
            {!receiptLog ? (
               <div className="flex-1 flex flex-col items-center justify-center text-slate-400 gap-4 min-h-[400px]">
                 <Loader2 className="w-12 h-12 animate-spin text-blue-500/20" />
                 <p className="font-medium tracking-widest uppercase text-sm">Listening for L6 Actions...</p>
                 <p className="text-xs max-w-xs text-center">Run a simulation that results in Eligibility to see a live receipt generated here.</p>
               </div>
            ) : (
             <AnimatePresence mode="wait">
              <motion.div 
                key={receiptLog.record_id}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                className="flex flex-col h-full"
              >
                <div className="flex justify-between items-start border-b-2 border-slate-200 pb-6 mb-8">
                  <div>
                    <h1 className="text-3xl font-black text-slate-900 tracking-tight">BENEFIT SUMMARY</h1>
                    <p className="font-mono text-slate-500 mt-1">ID: {receiptId}</p>
                  </div>
                  <div className="w-16 h-16 bg-blue-600 rounded-2xl flex items-center justify-center text-white font-bold text-2xl shadow-lg shadow-blue-500/40">JS</div>
                </div>

                <div className="grid grid-cols-2 gap-8 mb-8">
                   <div>
                      <p className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-1">Beneficiary Session</p>
                      <p className="font-bold text-lg text-slate-800 font-mono">{(receiptLog.session_id || 'Unknown').split('-').pop()}</p>
                      <p className="text-sm font-medium text-slate-600">Verified via telecom channel</p>
                   </div>
                   <div>
                      <p className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-1">Scheme Matched</p>
                      <p className="font-bold text-lg text-emerald-600">{schemeName as string}</p>
                      <p className="text-sm font-medium text-slate-600 flex items-center gap-1"><CheckCircle className="w-4 h-4 text-emerald-500" /> Eligible ({((receiptLog.payload?.rules_score as number) || 0) * 100}%)</p>
                   </div>
                </div>

                <div className="bg-slate-50 rounded-xl p-6 border border-slate-200 mb-8">
                   <h3 className="font-bold text-slate-800 mb-4 border-b border-slate-200 pb-2">Rule Verification Trace</h3>
                   <ul className="space-y-3 font-mono text-xs text-slate-600">
                     {rulesTrace.length > 0 ? rulesTrace.map((ruleText, idx) => (
                       <li key={idx} className="flex justify-between border-b border-slate-100 last:border-0 pb-1">
                         <span className="truncate pr-4">{ruleText}</span> 
                         <span className="text-emerald-600 font-bold shrink-0">PASS</span>
                       </li>
                     )) : (
                       <li className="flex justify-between"><span>Rule: LLM Override</span> <span className="text-emerald-600 font-bold">PASS</span></li>
                     )}
                   </ul>
                </div>

                <div className="mb-12">
                   <h3 className="font-bold text-slate-800 mb-4">Action Checklist for Citizen</h3>
                   <div className="space-y-3">
                      <div className="flex gap-3 items-start">
                         <div className="mt-0.5 w-5 h-5 rounded-full bg-blue-100 flex items-center justify-center text-blue-600 text-xs font-bold shrink-0">1</div>
                         <p className="text-sm font-medium text-slate-700">Visit nearest CSC (Common Service Center) with this receipt ID.</p>
                      </div>
                      <div className="flex gap-3 items-start">
                         <div className="mt-0.5 w-5 h-5 rounded-full bg-blue-100 flex items-center justify-center text-blue-600 text-xs font-bold shrink-0">2</div>
                         <p className="text-sm font-medium text-slate-700">Carry original physical Aadhaar Card for biometric confirmation.</p>
                      </div>
                   </div>
                </div>

                <div className="pt-6 border-t border-slate-200 flex justify-between items-center mt-auto">
                   <div className="flex gap-3">
                      <button className="p-2 border border-slate-200 hover:bg-slate-50 transition-colors rounded-lg text-slate-600"><Share2 className="w-4 h-4" /></button>
                      <button className="p-2 border border-slate-200 hover:bg-slate-50 transition-colors rounded-lg text-slate-600"><Printer className="w-4 h-4" /></button>
                   </div>
                   <div className="text-right">
                      <p className="text-[10px] uppercase font-bold text-slate-400">Digital Hash Signature</p>
                      <p className="font-mono text-[10px] text-slate-500">{receiptLog.integrity_hash.substring(0, 16)}...</p>
                   </div>
                </div>
              </motion.div>
             </AnimatePresence>
            )}
          </div>
        </div>

        {/* SMS Mock Panel */}
        <div className="col-span-1 flex flex-col items-center">
           <h3 className="w-full text-sm font-bold uppercase tracking-wider text-secondary-foreground mb-4">L7 Notifier: SMS Dispatch</h3>
           
           {/* Mock Phone Container */}
           <div className="w-[300px] h-[600px] bg-black rounded-[3rem] border-[12px] border-[#222] shadow-2xl relative overflow-hidden flex flex-col">
              {/* Dynamic Island */}
              <div className="absolute top-2 left-1/2 -translate-x-1/2 w-24 h-6 bg-black rounded-full z-20 shadow-md"></div>
             {/* Receipt Modal */}
            <div className="flex-1 bg-secondary/30 overflow-y-auto p-4 pt-12 flex flex-col gap-4 scrollbar-none relative">
              
              {/* Receipt Header (System Match) */}
                 <div className="text-center w-full mb-6">
                    <p className="text-white font-medium text-sm">JanSathi</p>
                    <p className="text-xs text-zinc-500">Service SMS</p>
                 </div>

                 {/* Mock messages */}
                 <div className="w-full flex">
                    <div className="bg-card text-foreground text-sm p-3 rounded-2xl rounded-tl-sm max-w-[85%] leading-relaxed shadow-md">
                       नमस्कार! JanSathi ने आपकी पात्रता जाँच ली है। आप <span className="font-bold text-emerald-400">PM-Kisan</span> के लिए पात्र हैं।
                    </div>
                 </div>
                 
                 <AnimatePresence>
                  {receiptLog && (
                   <motion.div 
                     initial={{ opacity: 0, y: 20, scale: 0.9 }}
                     animate={{ opacity: 1, y: 0, scale: 1 }}
                     transition={{ delay: 0.5, type: 'spring' }}
                     className="w-full flex mt-2"
                   >
                    <div className="flex flex-col gap-1 items-start w-full">
                     <span className="text-[10px] uppercase font-bold text-secondary-foreground ml-1 mb-1 tracking-widest opacity-60">
                        Aadhaar Encrypted Payload
                     </span>
                     <div className="bg-card text-foreground text-sm p-3 rounded-2xl rounded-tl-sm max-w-[85%] leading-relaxed shadow-md border border-border/50">
                        <pre className="font-mono text-xs overflow-x-auto text-emerald-600 dark:text-emerald-400">
{`{
  "tx_hash": "${txHash}",
  "status": "Verified",
  "timestamp": "${txTimestamp}"
}`}
                        </pre>
                     </div>
                     <div className="bg-card text-foreground text-sm p-3 rounded-2xl rounded-tl-sm max-w-[85%] leading-relaxed shadow-md border border-border/50">
                        <p className="mb-2">Your Benefit Receipt is ready. Receipt ID: <span className="font-mono font-bold text-[10px]">{receiptId}</span>.</p>
                        <p className="text-xs text-zinc-400 mb-3">Save this for the CSC center.</p>
                        <div className="w-full py-2 bg-blue-600/20 text-blue-400 text-center font-bold text-xs rounded-lg flex items-center justify-center gap-2">
                           <Download className="w-3 h-3" /> Download PDF
                        </div>
                     </div>
                    </div>
                   </motion.div>
                  )}
                 </AnimatePresence>
                 <span className="text-[10px] text-zinc-600 text-center w-full mt-1">Delivered • Today 14:30</span>
              </div>
           </div>
        </div>
      </div>
    </div>
  );
}
